freebsd_instance:
  image_family: freebsd-14-0-snap
task:
  install_script: pkg install -y git gmake gcc
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=g++ gmake
  tests_script: CXX=g++ gmake check
