task:
  name: freebsd-14-gcc
  freebsd_instance:
    image_family: freebsd-14-0
  install_script: pkg install -y git gmake gcc
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=g++ RANLIB=gcc-ranlib13 AR=gcc-ar13 gmake
  tests_script: CXX=g++ RANLIB=gcc-ranlib13 AR=gcc-ar13 gmake check
task:
  name: freebsd-14-gcc-conan
  freebsd_instance:
    image_family: freebsd-14-0
  install_script:
    - pkg install -y git gmake cmake gcc llvm15 devel/py-pip py311-sqlite3
    - pip install --user conan
    - ln -s /usr/local/bin/clang-format15 /usr/local/bin/clang-format
  script:
    - export CC=gcc CXX=g++ RANLIB=gcc-ranlib13 AR=gcc-ar13 PATH=~/.local/bin:$PATH
    - conan profile detect
    - echo -e "[platform_tool_requires]\ncmake/$(cmake --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')" >> ~/.conan2/profiles/default
    - conan install . --build=missing -s compiler.cppstd=20 -s compiler.libcxx=libstdc++11 --generator MakeDeps --output-folder build/conan
    - gmake all
  tests_script: CXX=g++ RANLIB=gcc-ranlib13 AR=gcc-ar13 gmake check
task:
  name: freebsd-14-gcc-cmake
  freebsd_instance:
    image_family: freebsd-14-0
  install_script:
    - pkg install -y git gmake cmake gcc llvm15 devel/py-pip py311-sqlite3
    - pip install --user conan
    - ln -s /usr/local/bin/clang-format15 /usr/local/bin/clang-format
  script:
    - export CC=gcc CXX=g++ RANLIB=gcc-ranlib13 AR=gcc-ar13 PATH=~/.local/bin:$PATH
    - mkdir build && cd build
    - conan profile detect
    - echo -e "[platform_tool_requires]\ncmake/$(cmake --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')" >> ~/.conan2/profiles/default
    - conan install .. --build missing -s compiler.cppstd=20 -s compiler.libcxx=libstdc++11
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${PWD} -DBUILD_TESTING=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_PREFIX=/tmp/install -DCMAKE_AR=`which $AR` -DCMAKE_RANLIB=`which $RANLIB`
    - cmake --build .
    - cmake --build . --target install
  tests_script: cd build && cmake --build . --target test
task:
  name: freebsd-14-clang
  freebsd_instance:
    image_family: freebsd-14-0
  install_script: pkg install -y git gmake binutils llvm15
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=clang++15 RANLIB=llvm-ranlib15 AR=llvm-ar15 gmake
  tests_script: CXX=clang++15 RANLIB=llvm-ranlib15 AR=llvm-ar15 gmake check
task:
  name: freebsd-14-clang-conan
  freebsd_instance:
    image_family: freebsd-14-0
  install_script:
    - pkg install -y git gmake cmake llvm15 binutils devel/py-pip py311-sqlite3
    - pip install --user conan
    - ln -s /usr/local/bin/clang-format15 /usr/bin/clang-format
  script:
    - export CC=clang15 CXX=clang++15 RANLIB=llvm-ranlib15 AR=llvm-ar15 PATH=~/.local/bin:$PATH
    - conan profile detect
    - echo -e "[platform_tool_requires]\ncmake/$(cmake --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')" >> ~/.conan2/profiles/default
    - conan install . --build=missing -s compiler.cppstd=20 --generator MakeDeps --output-folder build/conan
    - gmake all
  tests_script: CXX=clang++15 RANLIB=llvm-ranlib15 AR=llvm-ar15 gmake check
task:
  name: freebsd-14-clang-cmake
  freebsd_instance:
    image_family: freebsd-14-0
  install_script:
    - pkg install -y git gmake cmake llvm15 binutils devel/py-pip py311-sqlite3
    - pip install --user conan
    - ln -s /usr/local/bin/clang-format15 /usr/bin/clang-format
  script:
    - export CC=clang15 CXX=clang++15 RANLIB=llvm-ranlib15 AR=llvm-ar15 PATH=~/.local/bin:$PATH
    - mkdir build && cd build
    - conan profile detect
    - echo -e "[platform_tool_requires]\ncmake/$(cmake --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')" >> ~/.conan2/profiles/default
    - conan install .. --build missing -s compiler.cppstd=20
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${PWD} -DBUILD_TESTING=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_PREFIX=/tmp/install -DCMAKE_AR=`which $AR` -DCMAKE_RANLIB=`which $RANLIB`
    - cmake --build .
    - cmake --build . --target install
  tests_script: cd build && cmake --build . --target test
task:
  name: freebsd-13-gcc
  freebsd_instance:
    image_family: freebsd-13-3
  install_script: pkg install -y git gmake gcc
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=g++ RANLIB=gcc-ranlib13 AR=gcc-ar13 gmake
  tests_script: CXX=g++ RANLIB=gcc-ranlib13 AR=gcc-ar13 gmake check
task:
  name: freebsd-13-clang
  freebsd_instance:
    image_family: freebsd-13-3
  install_script: pkg install -y git gmake binutils llvm15
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=clang++15 RANLIB=llvm-ranlib15 AR=llvm-ar15 gmake
  tests_script: CXX=clang++15 RANLIB=llvm-ranlib15 AR=llvm-ar15 gmake check
