task:
  name: freebsd-14-gcc
  freebsd_instance:
    image_family: freebsd-14-3
  install_script: pkg install -y git gmake gcc14
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=g++14 RANLIB=gcc-ranlib14 AR=gcc-ar14 gmake
  tests_script: CXX=g++14 RANLIB=gcc-ranlib14 AR=gcc-ar14 gmake check
task:
  name: freebsd-14-gcc-conan
  freebsd_instance:
    image_family: freebsd-14-3
  install_script:
    - pkg install -y git gmake cmake gcc14 llvm18 devel/py-pip py311-sqlite3
    - pip install --user conan
    - ln -s /usr/local/bin/clang-format18 /usr/local/bin/clang-format
  script:
    - export CC=gcc14 CXX=g++14 RANLIB=gcc-ranlib14 AR=gcc-ar14 PATH=~/.local/bin:$PATH
    - conan profile detect
    - conan install . --build missing -s compiler.libcxx=libstdc++11
    - gmake all
  tests_script: CXX=g++14 RANLIB=gcc-ranlib14 AR=gcc-ar14 gmake check
task:
  name: freebsd-14-gcc-cmake
  freebsd_instance:
    image_family: freebsd-14-3
  install_script:
    - pkg install -y git gmake cmake gcc14 llvm18 devel/py-pip py311-sqlite3
    - pip install --user conan
    - ln -s /usr/local/bin/clang-format18 /usr/local/bin/clang-format
  script:
    - export CC=gcc14 CXX=g++14 RANLIB=gcc-ranlib14 AR=gcc-ar14 PATH=~/.local/bin:$PATH
    - mkdir build && cd build
    - conan profile detect
    - conan install .. -g CMakeDeps -g CMakeToolchain --output-folder=${PWD} --build missing -s compiler.libcxx=libstdc++11
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DBUILD_TESTING=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_PREFIX=/tmp/install -DCMAKE_AR=`which $AR` -DCMAKE_RANLIB=`which $RANLIB`
    - cmake --build .
    - cmake --build . --target install
  tests_script: cd build && cmake --build . --target test
task:
  name: freebsd-14-clang
  freebsd_instance:
    image_family: freebsd-14-3
  install_script: pkg install -y git gmake binutils llvm18
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=clang++18 RANLIB=llvm-ranlib18 AR=llvm-ar18 gmake
  tests_script: CXX=clang++18 RANLIB=llvm-ranlib18 AR=llvm-ar18 gmake check
task:
  name: freebsd-14-clang-conan
  freebsd_instance:
    image_family: freebsd-14-3
  install_script:
    - pkg install -y git gmake cmake llvm18 binutils devel/py-pip py311-sqlite3
    - pip install --user conan
    - ln -s /usr/local/bin/clang-format18 /usr/bin/clang-format
  script:
    - export CC=clang18 CXX=clang++18 RANLIB=llvm-ranlib18 AR=llvm-ar18 PATH=~/.local/bin:$PATH
    - conan profile detect
    - conan install . --build missing
    - gmake all
  tests_script: CXX=clang++18 RANLIB=llvm-ranlib18 AR=llvm-ar18 gmake check
task:
  name: freebsd-14-clang-cmake
  freebsd_instance:
    image_family: freebsd-14-3
  install_script:
    - pkg install -y git gmake cmake llvm18 binutils devel/py-pip py311-sqlite3
    - pip install --user conan
    - ln -s /usr/local/bin/clang-format18 /usr/bin/clang-format
  script:
    - export CC=clang18 CXX=clang++18 RANLIB=llvm-ranlib18 AR=llvm-ar18 PATH=~/.local/bin:$PATH
    - mkdir build && cd build
    - conan profile detect
    - conan install .. -g CMakeDeps -g CMakeToolchain --output-folder=${PWD} --build missing
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DBUILD_TESTING=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_PREFIX=/tmp/install -DCMAKE_AR=`which $AR` -DCMAKE_RANLIB=`which $RANLIB`
    - cmake --build .
    - cmake --build . --target install
  tests_script: cd build && cmake --build . --target test
task:
  name: freebsd-13-gcc
  freebsd_instance:
    image_family: freebsd-13-5
  install_script: pkg install -y git gmake gcc14
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=g++14 RANLIB=gcc-ranlib14 AR=gcc-ar14 gmake
  tests_script: CXX=g++14 RANLIB=gcc-ranlib14 AR=gcc-ar14 gmake check
task:
  name: freebsd-13-clang
  freebsd_instance:
    image_family: freebsd-13-5
  install_script: pkg install -y git gmake binutils llvm18
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=clang++18 RANLIB=llvm-ranlib18 AR=llvm-ar18 gmake
  tests_script: CXX=clang++18 RANLIB=llvm-ranlib18 AR=llvm-ar18 gmake check
