task:
  name: freebsd-14-gcc
  freebsd_instance:
    image_family: freebsd-14-0-snap
  install_script: pkg install -y git gmake gcc
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10 gmake
  tests_script: CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10 gmake check
task:
  name: freebsd-14-gcc-conan
  freebsd_instance:
    image_family: freebsd-14-0-snap
  install_script:
    - pkg install -y git gmake cmake gcc conan llvm13
    - ln -s /usr/local/bin/clang-format13 /usr/local/bin/clang-format
  script:
    - export CC=gcc CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10
    - conan install . --build missing -s compiler.libcxx=libstdc++11
    - gmake all
  tests_script: CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10 gmake check
task:
  name: freebsd-14-gcc-cmake
  freebsd_instance:
    image_family: freebsd-14-0-snap
  install_script:
    - pkg install -y git gmake cmake gcc conan llvm13
    - ln -s /usr/local/bin/clang-format13 /usr/local/bin/clang-format
  script:
    - export CC=gcc CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10
    - mkdir build && cd build
    - conan install .. -g cmake_find_package --build missing -s compiler.libcxx=libstdc++11
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_MODULE_PATH=${PWD} -DBUILD_TESTING=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_PREFIX=/tmp/install -DCMAKE_AR=`which $AR` -DCMAKE_RANLIB=`which $RANLIB`
    - cmake --build .
    - cmake --build . --target install
  tests_script: cd build && cmake --build . --target test
task:
  name: freebsd-14-clang
  freebsd_instance:
    image_family: freebsd-14-0-snap
  install_script: pkg install -y git gmake binutils llvm13
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=clang++13 RANLIB=llvm-ranlib13 AR=llvm-ar13 gmake
  tests_script: CXX=clang++13 RANLIB=llvm-ranlib13 AR=llvm-ar13 gmake check
task:
  name: freebsd-14-clang-conan
  freebsd_instance:
    image_family: freebsd-14-0-snap
  install_script:
    - pkg install -y git gmake cmake conan llvm13 binutils
    - ln -s /usr/local/bin/clang-format13 /usr/bin/clang-format
  script:
    - export CC=clang13 CXX=clang++13 RANLIB=llvm-ranlib13 AR=llvm-ar13
    - conan install . --build missing
    - gmake all
  tests_script: CXX=clang++13 RANLIB=llvm-ranlib13 AR=llvm-ar13 gmake check
task:
  name: freebsd-14-clang-cmake
  freebsd_instance:
    image_family: freebsd-14-0-snap
  install_script:
    - pkg install -y git gmake cmake conan llvm13 binutils
    - ln -s /usr/local/bin/clang-format13 /usr/bin/clang-format
  script:
    - export CC=clang13 CXX=clang++13 RANLIB=llvm-ranlib13 AR=llvm-ar13
    - mkdir build && cd build
    - conan install .. -g cmake_find_package --build missing
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_MODULE_PATH=${PWD} -DBUILD_TESTING=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_PREFIX=/tmp/install -DCMAKE_AR=`which $AR` -DCMAKE_RANLIB=`which $RANLIB`
    - cmake --build .
    - cmake --build . --target install
  tests_script: cd build && cmake --build . --target test
task:
  name: freebsd-13-gcc
  freebsd_instance:
    image_family: freebsd-13-0
  install_script: pkg install -y git gmake gcc
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10 gmake
  tests_script: CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10 gmake check
task:
  name: freebsd-13-clang
  freebsd_instance:
    image_family: freebsd-13-0
  install_script: pkg install -y git gmake binutils llvm12
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=clang++12 RANLIB=llvm-ranlib12 AR=llvm-ar12 gmake
  tests_script: CXX=clang++12 RANLIB=llvm-ranlib12 AR=llvm-ar12 gmake check
