task:
  name: freebsd-14-gcc
  freebsd_instance:
    image_family: freebsd-14-0-snap
  install_script: pkg install -y git gmake gcc
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10 gmake
  tests_script: CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10 gmake check
task:
  name: freebsd-14-gcc-conan
  freebsd_instance:
    image_family: freebsd-14-0-snap
  install_script:
    - pkg install -y git gmake cmake gcc conan llvm12
    - ln -s /usr/local/bin/clang-format12 /usr/bin/clang-format
  script:
    - export CC=gcc CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10
    - conan install . --build missing -s compiler.libcxx=libstdc++11
    - gmake all
  tests_script: CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10 gmake check
task:
  name: freebsd-14-clang
  freebsd_instance:
    image_family: freebsd-14-0-snap
  install_script: pkg install -y git gmake gcc llvm12
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=clang++12 RANLIB=llvm-ranlib12 AR=llvm-ar12 gmake
  tests_script: CXX=clang++12 RANLIB=llvm-ranlib12 AR=llvm-ar12 gmake check
task:
  name: freebsd-14-clang-conan
  freebsd_instance:
    image_family: freebsd-14-0-snap
  install_script:
    - pkg install -y git gmake cmake conan llvm12
    - ln -s /usr/local/bin/clang-format12 /usr/bin/clang-format
  script:
    - export CC=clang CXX=clang++12 RANLIB=llvm-ranlib12 AR=llvm-ar12
    - conan install . --build missing -s compiler=clang -s compiler.libcxx=libstdc++11
    - gmake all
  tests_script: CXX=clang++12 RANLIB=llvm-ranlib12 AR=llvm-ar12 gmake check
task:
  name: freebsd-13-gcc
  freebsd_instance:
    image_family: freebsd-13-0
  install_script: pkg install -y git gmake gcc
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10 gmake
  tests_script: CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10 gmake check
task:
  name: freebsd-13-clang
  freebsd_instance:
    image_family: freebsd-13-0
  install_script: pkg install -y git gmake gcc llvm12
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=clang++12 RANLIB=llvm-ranlib12 AR=llvm-ar12 gmake
  tests_script: CXX=clang++12 RANLIB=llvm-ranlib12 AR=llvm-ar12 gmake check
