task:
  name: freebsd-14-gcc
  freebsd_instance:
    image_family: freebsd-14-0-snap
  install_script: pkg install -y git gmake gcc
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10 gmake
  tests_script: CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10 gmake check
task:
  name: freebsd-13-gcc
  freebsd_instance:
    image_family: freebsd-13-0
  install_script: pkg install -y git gmake gcc
  submodules_script:
    - git submodule init
    - git submodule update
  script: CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10 gmake
  tests_script: CXX=g++ RANLIB=gcc-ranlib10 AR=gcc-ar10 gmake check
