name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4

    - name: install packages
      run: |
        sudo apt-get install doxygen
        pip install 'sphinx<7.2'
        pip install breathe
        pip install sphinx-rtd-theme
    - name: make docs
      run: make -B docs
    - name: Commit changes
      if: github.ref == 'refs/heads/master'
      uses: EndBug/add-and-commit@v9
      with:
        author_name: github-actions
        author_email: github-actions@github.com
        message: 'Update documentation'
        add: -u docs
