name: MacOS-GCC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        except: [1, 0]
    steps:
    - uses: actions/checkout@v2

    - name: install gcc
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        brew install gcc@10

    - name: init submodules
      run: git submodule init
    - name: update submodules
      run: git submodule update

    - name: make
      run: make CXX=g++-10 RANLIB=gcc-ranlib-10 AR=gcc-ar-10 -j2 EXCEPTIONS=${{matrix.except}}
    - name: test
      run: make CXX=g++-10 RANLIB=gcc-ranlib-10 AR=gcc-ar-10 -j2 EXCEPTIONS=${{matrix.except}} check

