name: Single include

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install gcc
      run: |
        sudo apt-get install g++-10
        sudo update-alternatives \
          --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
          --slave /usr/bin/g++ g++ /usr/bin/g++-10 \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-10 \
          --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-10 \
          --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-10
    - name: init submodules
      run: git submodule init
    - name: update submodules
      run: git submodule update

    - name: make header
      run: make single_include

    - name: build
      run: g++ -DFMT_HEADER_ONLY -std=c++20 -Wall -pedantic test/single_include.cpp -I single_include -isystem third_party/include -pthread -o /dev/null

    - name: commit and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git pull github ${GITHUB_REF} --ff-only
        git diff-index --quiet HEAD && git pull && git commit -m 'Update single include' single_include/xtr/logger.hpp
        git push github HEAD:${GITHUB_REF}
