name: Single include

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: init submodules
      run: git submodule init
    - name: update submodules
      run: git submodule update

    - name: make header
      run: make -B single_include

    - name: build
      run: g++ -DFMT_HEADER_ONLY -std=c++20 -Wall -pedantic test/single_include.cpp -I single_include -isystem third_party/include -pthread -o /dev/null

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions
        author_email: github-actions@github.com
        message: 'Update single include header'
        add: single_include/xtr/logger.hpp
