name: Single include

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y --no-install-recommends pkg-config python3-venv
        make conan-profile
        make build/pkgconfig/fmt.pc

    - name: make header
      run: make -B single_include

    - name: build
      run: g++ -DXTR_USE_IO_URING=0 -std=c++20 -Wall -pedantic test/single_include.cpp -I single_include $(PKG_CONFIG_PATH=build/pkgconfig pkg-config --cflags --libs fmt) -pthread -o /dev/null

    - name: Commit changes
      if: github.ref == 'refs/heads/master'
      uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
      with:
        author_name: github-actions
        author_email: github-actions@github.com
        message: 'Update single include header'
        add: single_include/xtr/logger.hpp
        pull: '--rebase --autostash'
