name: Ubuntu-GCC-Sanitizer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [address, undefined, thread leak]
        exceptions: [1, 0]
    steps:
    - uses: actions/checkout@v2
    - name: install gcc
      run: |
        sudo apt-get install g++-10
        sudo update-alternatives \
          --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
          --slave /usr/bin/g++ g++ /usr/bin/g++-10 \
          --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-10 \
          --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-10
    - name: init submodules
      run: git submodule init
    - name: update submodules
      run: git submodule update
    - name: sanitizer
      run: make -j2 EXCEPTIONS=${{matrix.exceptions}} SANITIZER=${{matrix.sanitizer}} check

