name: Ubuntu-GCC-Sanitizer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [address, undefined, thread, leak]
        except: [1, 0]
    steps:
    - uses: actions/checkout@v2
    - name: install gcc
      run: |
        sudo update-alternatives \
          --install /usr/bin/gcc gcc /usr/bin/gcc-11 1000 \
          --slave /usr/bin/g++ g++ /usr/bin/g++-11 \
          --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-11 \
          --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-11
    - name: init submodules
      run: git submodule init
    - name: update submodules
      run: git submodule update
    - name: sanitizer
      run: make -j2 EXCEPTIONS=${{matrix.except}} SANITIZER=${{matrix.sanitizer}} check

