name: Ubuntu-Clang

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        except: [1, 0]
        pic: [1, 0]
        rtti: [1, 0]
    steps:
    - uses: actions/checkout@v2

    - name: setup clang
      run: |
        sudo update-alternatives \
          --install /usr/lib/llvm llvm /usr/lib/llvm-19 1000 \
          --slave /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-19 \
          --slave /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-19
        sudo update-alternatives \
          --install /usr/bin/clang clang /usr/bin/clang-19 1000
        sudo update-alternatives \
          --install /usr/bin/clang++ clang++ /usr/bin/clang++-19 1000

    - name: init submodules
      run: git submodule init
    - name: update submodules
      run: git submodule update

    - name: make
      run: CXX=clang++ AR=llvm-ar RANLIB=llvm-ranlib make -j2 EXCEPTIONS=${{matrix.except}} PIC=${{matrix.pic}} RTTI=${{matrix.rtti}}
    - name: test
      run: CXX=clang++ AR=llvm-ar RANLIB=llvm-ranlib make -j2 EXCEPTIONS=${{matrix.except}} PIC=${{matrix.pic}} RTTI=${{matrix.rtti}} check
