name: Ubuntu-Clang

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        except: [1, 0]
        pic: [1, 0]
        rtti: [1, 0]
    steps:
    - uses: actions/checkout@v2

    - name: init submodules
      run: git submodule init
    - name: update submodules
      run: git submodule update

    - name: make
      run: CXX=clang++-12 make -j2 EXCEPTIONS=${{matrix.except}} PIC=${{matrix.pic}} RTTI=${{matrix.rtti}}
    - name: test
      run: CXX=clang++-12 make -j2 EXCEPTIONS=${{matrix.except}} PIC=${{matrix.pic}} RTTI=${{matrix.rtti}} check
