name: Ubuntu-GCC-Conan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install gcc
      run: |
        sudo apt-get install g++-10
        sudo update-alternatives \
          --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
          --slave /usr/bin/g++ g++ /usr/bin/g++-10 \
          --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-10 \
          --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-10
          
    - name: install conan
      run: sudo pip install conan
    - name: install dependencies
      run: conan install . --build missing -s compiler.libcxx=libstdc++11

    - name: make 
      run: make -j2
    - name: test
      run: make -j2 run_test

    - name: make no-exceptions
      run: make -j2 EXCEPTIONS=0
    - name: test no-exceptions
      run: make -j2 EXCEPTIONS=0 run_test

