name: Ubuntu-Clang

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        except: [1, 0]
        pic: [1, 0]
        rtti: [1, 0]
    steps:
    - uses: actions/checkout@v2

    - name: install clang
      run: sudo apt-get install clang++-12 llvm-12

    - name: init submodules
      run: git submodule init
    - name: update submodules
      run: git submodule update

    - name: make
      run: CXX=clang++ make -j2 EXCEPTIONS=${{matrix.except}} PIC=${{matrix.pic}} RTTI=${{matrix.rtti}}
    - name: test
      run: CXX=clang++ make -j2 EXCEPTIONS=${{matrix.except}} PIC=${{matrix.pic}} RTTI=${{matrix.rtti}} check
