name: Ubuntu-Clang-Sanitizer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [address, undefined, thread, leak]
        except: [1, 0]
    steps:
    - uses: actions/checkout@v2

    - name: init submodules
      run: git submodule init
    - name: update submodules
      run: git submodule update

    - name: sanitizer
      run: CXX=clang++ AR=llvm-ar RANLIB=llvm-ranlib make -j2 EXCEPTIONS=${{matrix.except}} SANITIZER=${{matrix.sanitizer}} check
