name: Ubuntu-Clang-Sanitizer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [address, undefined, thread, leak]
        except: [1, 0]
    steps:
    - uses: actions/checkout@v2

    - name: set symlinks
      run: |
        sudo update-alternatives --install /usr/lib/llvm llvm /usr/lib/llvm-15 1000
        sudo update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-15 1000
        sudo update-alternatives --install /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-15 1000
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-15 1000
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-15 1000
        sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-15 1000

    - name: init submodules
      run: git submodule init
    - name: update submodules
      run: git submodule update

    - name: sanitizer
      run: CXX=clang++ make -j2 EXCEPTIONS=${{matrix.except}} SANITIZER=${{matrix.sanitizer}} check
